-- To see all databses
SHOW DATABASES;
SELECT * FROM RGM;
-- UPDATE  -- NORMALLY TURNED OFF IN SQL WORKBENCH CHANGE SETTINGS FOR THE FIRST TIME IN SETTINGS->PREFERENCES->SQL EDITOR->LAST SAFE UPDATES CHECKBOX
UPDATE RGM SET NAME="SAINADH" WHERE CONTACT = 12222; 
-- UPDATE FOR MULTIPLE VALUES
UPDATE RGM SET SESSION="JAVA" , ADDRESS = "NANDYAL" WHERE CONTACT=14444;
-- NEW TABLE
CREATE TABLE TEST(
	STUDENT_ID INT PRIMARY KEY,
    STUDENT_NAME VARCHAR(30),
    STUDENT_CONTACT INT,
    STUDENT_DEPT VARCHAR(20)
    );
SELECT * FROM TEST;
-- COPYING DATA FROM ONE TABLE TO ANOTHER WITH SAME COLUMN NAMES -- IT NEEDS TO BE IN SAME DATABASE
INSERT INTO TEST SELECT * FROM STUDENT; -- INSERT VALUES FROM STUDENT TABLE TO TEST TABLE
-- REMOVE ALL DATA FROM TABLE
TRUNCATE TABLE TEST;
-- DELETE
DELETE FROM STUDENT WHERE STUDENT_NAME="REDDY"; -- DELETE ENTIRE ROW
SELECT * FROM STUDENT;
-- DROP DELETE ENTIRE TABLE AND SCHEMA
DROP TABLE TEST;
-- ALTER COMMANDS
-- CHANGING COLUMN NAME USING ALTER RENAME
ALTER TABLE STUDENT RENAME COLUMN STUDENT_NAME TO NAME;
-- CHANGING TABLE NAME
ALTER TABLE STUDENT RENAME TO RGM_STUDENT;
SELECT * FROM RGM_STUDENT;
-- DROPING A DATABASE
CREATE DATABASE SUNS;
SHOW DATABASES;
DROP DATABASE SUNS;
-- ALTER ADD
ALTER TABLE RGM_STUDENT ADD ADDRESS VARCHAR(30);
-- UPDATING DATABASE
UPDATE RGM_STUDENT SET ADDRESS="NELLORE" WHERE STUDENT_ID = "101";
-- CHANGING DATA TYPE
ALTER TABLE RGM_STUDENT MODIFY COLUMN ADDRESS VARCHAR(50);
-- DROP ENTIRE COLUMN
ALTER TABLE RGM_STUDENT DROP COLUMN ADDRESS;