CREATE DATABASE EXERCISE;
CREATE TABLE CUSTOMER(ID INT PRIMARY KEY,NAME VARCHAR(20),CITY VARCHAR(30),GRADE INT,SALESMAN_ID INT);
INSERT INTO CUSTOMER VALUES(101,"SUDARSHAN","VIZAG",190,201),
	(102,"DILEEP","MUMBAI",192,202),
    (103,"YASWANTH","KOLKATTA",192,203),
    (104,"SURESH","HYDERABAD",189,204),
    (105,"SHANTHAN","CHENNAI",180,205),
    (106,"VINAY","DELHI",172,206),
    (107,"VEERA","MUMBAI",90,207),
    (108,"REDDY","VIZAG",99,208);
SELECT * FROM CUSTOMER;

-- WRITE A SQL QUERY TO FIND OUT THE DETAILS OF THE CUSTOMER WHOSE GRADE ARE ABOVE 100
SELECT * FROM CUSTOMER WHERE GRADE > 100;
-- WRITE A SQL QUERY TO FIND OUT THE DETAILS OF THE CUSTOMER WHOSE GRADE ARE ABOVE OR EQUAL TO 100
SELECT * FROM CUSTOMER WHERE GRADE >= 100;
-- WRITE A SQL QUERY TO FIND OUT THE DETAILS OF THE CUSTOMER WHOSE GRADE ARE ABOVE 100 IN ASCENDING ORDER
SELECT * FROM CUSTOMER WHERE GRADE > 100 ORDER BY GRADE;
-- OR SELECT * FROM CUSTOMER WHERE GRADE > 100 ORDER BY GRADE ASC;
-- WRITE A SQL QUERY TO FIND OUT THE DETAILS OF THE CUSTOMER WHOSE GRADE IS ABOVE 100 AND CITY IS HYDERABAD
SELECT * FROM CUSTOMER WHERE CITY = "HYDERABAD" AND GRADE > 100;
-- WRITE A SQL QUERY TO FIND OUT THE DETAILS OF THE CUSTOMER WHOSE GRADE IS ABOVE 100 OR CITY IS HYDERABAD
SELECT * FROM CUSTOMER WHERE CITY = "HYDERABAD" OR GRADE > 100;