CREATE TABLE STUDENT(
	STUDENT_ID INT PRIMARY KEY,
    STUDENT_NAME VARCHAR(20),
    STUDENT_MARKS INT
    );
INSERT INTO STUDENT VALUES(101,"SUDARSHAN",90);
INSERT INTO STUDENT VALUES(102,"DILEEP",80);
INSERT INTO STUDENT VALUES(103,"VINAY",70);
INSERT INTO STUDENT VALUES(104,"SHANTHAN",90);
INSERT INTO STUDENT VALUES(105,"YASWANTH",85);
INSERT INTO STUDENT VALUES(106,"SURESH",80);
INSERT INTO STUDENT VALUES(107,"REDDY",83);
INSERT INTO STUDENT VALUES(108,"VEERA",90);

-- EQUAL
SELECT * FROM STUDENT WHERE STUDENT_MARKS = 80;
-- LESS THAN
SELECT * FROM STUDENT WHERE STUDENT_MARKS < 80;
-- LESS THAN OR EQUAL
SELECT * FROM STUDENT WHERE STUDENT_MARKS <= 80;
-- NOT EQUAL
SELECT * FROM STUDENT WHERE STUDENT_MARKS != 80;
-- ANOTHER WAY OF USING NOT EQUAL
SELECT * FROM STUDENT WHERE STUDENT_MARKS <> 80;
-- BETWEEN
SELECT * FROM STUDENT WHERE STUDENT_MARKS BETWEEN 80 AND 90;
-- ASCENDING OR DESCENDING ORDER USING ORDER BY
-- DEFAULT ASCENDING ORDER
SELECT * FROM STUDENT WHERE STUDENT_MARKS BETWEEN 80 AND 90 ORDER BY STUDENT_MARKS;
-- OR ASCENDENIG SPECIFIED ASC
SELECT * FROM STUDENT WHERE STUDENT_MARKS BETWEEN 80 AND 90 ORDER BY STUDENT_MARKS ASC;
-- DESCENDING ORDER SPECIFY DESC
SELECT * FROM STUDENT WHERE STUDENT_MARKS BETWEEN 80 AND 90 ORDER BY STUDENT_MARKS DESC;
-- WHERE NOT
SELECT * FROM STUDENT WHERE NOT STUDENT_MARKS = 90;
-- DISTINCT
SELECT DISTINCT STUDENT_MARKS FROM STUDENT;
-- COUNT
SELECT COUNT(distinct STUDENT_MARKS) FROM STUDENT;
-- LIMIT
SELECT * FROM STUDENT LIMIT 3;
SELECT * FROM STUDENT WHERE STUDENT_MARKS=90 LIMIT 1;
SELECT * FROM STUDENT WHERE STUDENT_MARKS=90;
-- GROUP BY
SELECT COUNT(STUDENT_MARKS),STUDENT_MARKS FROM STUDENT GROUP BY STUDENT_MARKS;
SELECT * FROM STUDENT ORDER BY STUDENT_ID DESC LIMIT 5;
CREATE TABLE DOB(
	DATE_ DATE NOT NULL
    );
INSERT INTO DOB VALUES("2002-10-12");
SELECT * FROM DOB;