CREATE DATABASE HEROVIRED;
CREATE TABLE RGM (
	ID INT primary KEY NOT NULL,
	NAME VARCHAR(30),
    COLLEGE VARCHAR(30),
    SESSION VARCHAR(20),
    CONTACT INT,
    ADDRESS VARCHAR(30)student
);

INSERT INTO RGM VALUES(101,"SUDARSHAN","RGM","GIT",12345,"NELLORE");
INSERT INTO RGM VALUES(102,"DILEEP","SVR","PYTHON",11111,"MYDUKUR");
INSERT INTO RGM VALUES(103,"VINAY","SVR","SQL",12222,"NANDIKOTKUR");
INSERT INTO RGM VALUES(104,"SHANTHAN","GPR","JAVA",13333,"HINDUPUR");
INSERT INTO RGM VALUES(105,"YASWANTH","GPR","PYTHON",14444,"KURNOOL");
INSERT INTO RGM VALUES(106,"SURESH","GPE","SQL",15555,"NANDYAL");
INSERT INTO RGM VALUES(107,"REDDY","GPE","SQL",16666,"NELLORE");

SELECT * FROM RGM WHERE COLLEGE="RGM";
SELECT  ID,NAME,SESSION FROM RGM WHERE SESSION="JAVA";
SELECT * FROM RGM WHERE NAME LIKE "S%";	-- STARTING LETTER
SELECT * FROM RGM WHERE NAME LIKE "SU%";
SELECT * FROM RGM WHERE NAME LIKE "%Y";	-- ENDING LETTER
SELECT * FROM RGM WHERE NAME LIKE "%N"; 
SELECT * FROM RGM WHERE NAME LIKE "_U%"; -- SECOND LETTER
SELECT * FROM RGM WHERE NAME LIKE "_U_______"; -- NUMBER OF UNDERSCORES NUMBER OF CHARACTERS

-- NOT LIKE
SELECT * FROM RGM WHERE NAME NOT LIKE "S%"; -- NOT STARTING WITH S
SELECT * FROM RGM WHERE NAME NOT LIKE "S%"; -- NOT STARTING WITH S

-- IN
SELECT * FROM RGM WHERE ADDRESS IN ("NANDYAL","KURNOOL");
SELECT * FROM RGM WHERE COLLEGE IN ("RGM","GPR");

-- WHERE AND
SELECT * FROM RGM WHERE COLLEGE = "RGM" OR COLLEGE = "GPR";
-- COUNT

-- DISTINCT
SELECT COUNT(DISTINCT ADDRESS) FROM RGM;
